module.exports = {
  plugins: ['react', 'react-hooks', 'import', 'prettier'],
  overrides: [
    {
      files: ['**/*.ts', '**/*.tsx'],
      parser: '@typescript-eslint/parser',
      extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/eslint-recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:import/errors',
        'plugin:import/typescript',
        'plugin:import/warnings',
        'plugin:prettier/recommended',
        'plugin:react/recommended',
        'prettier',
        'prettier/@typescript-eslint',
        'prettier/react',
      ],
      rules: {
        '@typescript-eslint/camelcase': 0,
        '@typescript-eslint/explicit-function-return-type': 0,
        '@typescript-eslint/no-explicit-any': 0,
        '@typescript-eslint/no-misused-promises': 0,
        '@typescript-eslint/no-unused-vars': [
          1,
          {
            args: 'none',
          },
        ],
        '@typescript-eslint/no-use-before-define': 0,
        'import/named': 0,
        'import/no-duplicates': 0,
        'import/no-named-as-default': 0,
        'import/no-unresolved': 0,
        'import/order': 1,
        'no-async-promise-executor': 0,
        'no-shadow': 1,
        'react-hooks/exhaustive-deps': 1,
        'react-hooks/rules-of-hooks': 2,
        'react/display-name': 0,
        'react/no-unescaped-entities': 0,
        'react/prop-types': 0,
      },
    },
  ],
};
